config/torchcraft.ini

The examples assume 11111 as default, so we should the same in the default `torchcraft.ini`.

Use 11111 as default port

---

client/client.cpp
client/client.h
client/client_lua.cpp
client/client_lua.h
client/lua.cpp
client/state.cpp
client/state.h
client/state_lua.cpp
client/state_lua.h
init.lua

This adds a client state definition to the C++ code, including some rudimentary
management logic. The state is attached to the Client object and extensible in
Lua, i.e. it can be used as a normal table for fields that are not pre-defined.
The client functionality has been changed from RAII to explicit initialization
via connect() and close(). This makes life easier in Lua since the same client
and state object can be passed around and will remaining valid after
re-connects.

Explicit C++-side client state

---

BWEnv/VisualStudio/BWEnv.vcxproj
BWEnv/fbs/messages.fbs
BWEnv/fbs/messages_generated.h
BWEnv/include/ZMQ_server.h
BWEnv/include/controller.h
BWEnv/include/utils.h
BWEnv/src/controller.cc
BWEnv/src/module.cc
BWEnv/src/utils.cc
BWEnv/src/zmq_server.cc

These are the server-side changes for changing the wire protocol to flatbuffers.
The code in ZMQ_server.h has been substantially simplified as there's no need to
parse strings anymore.

Use flatbuffers for wire protocol (server-side changes)

---

CMakeLists.txt
client/client.cpp
client/client.h
client/client_lua.cpp
client/lua_utils.h
client/state.cpp
client/state.h
client/state_lua.cpp
client/state_lua.h
examples/baseline_heuristics.lua
examples/self_play_dll.lua
examples/simple_dll.lua
examples/simple_exe.lua
examples/tensor_example.lua
examples/visual_example.lua
init.lua
replayer/frame_lua.h

This ports the remaining logic from torchcraft:receive() to the C++ State
object. In particular, client::State now keeps track of units that are alive,
similar to what the Lua code has been doing previously with `units_myself`,
`units_enemy` and so on. Unfortunately, this requires maintaining a
near-duplicate of frame->units so that client code is able to work with the
correct units if frame skipping is enabled on the server (and thus frame->units
might include units that have died since the previous update).
Another significant change is that the `torchcraft.mode` has been removed.
Previously, it was a mix of a setup option (`micro_battles`), a constant
determined by the map (`replay`) and a way to tune end-of-battle detection
(`only_consider_units`). `micro_battles` and …

Active unit tracking and end-of-battle detection in client::State

---

torchcraft-1.0-2.rockspec

Client-server communication is handled in the C++ client module.

Removed lzmq dependency from rockspec

---

client/constants.h
client/constants_lua.cpp
client/lua_utils.h

A few scalar constants got lost in the transition to C++. They were declared in
constants.h but not added to the `client.const` Lua table.

Add missing scalars to client.const

---

client.lua
client/client.cpp
client/connection.cpp
client/connection.h
client/constants.cpp
client/constants_static.cpp
client/state.cpp
include/client.h
include/constants.h
include/frame.h
include/state.h
init.lua
lua/client_lua.cpp
lua/client_lua.h
lua/constants_lua.cpp
lua/constants_lua.h
lua/frame_lua.cpp
lua/frame_lua.h
lua/gamestore.cpp
lua/gamestore.h
lua/init.cpp
lua/lua_utils.cpp
lua/lua_utils.h
lua/replayer.cpp
lua/replayer.h
lua/state_lua.cpp
lua/state_lua.h
replayer/frame.cpp

C++ side: `client` is now `torchcraft`, and `replayer` resides in
`torchcraft::replayer`
Lua side: `torchcraft.client` is gone and the corresponding definitions have
moved to the top-level `torchcraft` module (this is done in `init.lua`).
`torchcraft.replayer` is available just like before. Importing the C++ module
will now return a table with definitions designated to the top-level module as
well as a sub-table for `replayer`.

Refactored C++ and Lua namespaces

---

client/connection.cpp

EAGAIN error on socket send / receive timeout does not throw zmq::error_t and returns false. Need to handle false return status separately from exception handling to treat the EAGAIN error properly.

special treatment of EAGAIN error on send/receive timeout

---

BWEnv/fbs/messages.fbs
BWEnv/fbs/messages_generated.h
client/client.cpp
include/client.h

The purpose of this field is to make it easy to extend client-server
communication with custom scripts. For example, a client-side ID enables
association of REQ messages with a specific session. It is currently used by the
client only (on a per-connection basis) and ignored by the server.

Add sender uid field to flatbuffer message

---

BWEnv/src/controller.cc
BWEnv/src/utils.cc
lua/client_lua.cpp

This commit fixes https://github.com/TorchCraft/TorchCraft/issues/34 plus set_map not working anymore due to the flatbuffer commit. Tested on simple_dll.lua, and checked that `mapiteration=RANDOM` was not overwritten by set_map.

Fixing set_map and overwriteConfig

---

BWEnv/include/controller.h
BWEnv/src/controller.cc
include/constants.h
lua/constants_lua.cpp

This adds a few basic commands that map to BWAPI's draw* functions for easy
client-side visualizations. Drawing commands are buffered in the controller,
executed at each frame and cleared before new client commands are being
received. For convenience, a few basic color values from StarCraft's palette
have been added to constants.h (taken from BWAPILIB/Source/Color.cpp).

Basic drawing commands

---

init.lua

pcall should take a function as its argument, not the result of a function call

correct invalid use of pcall in torchcraft:init

---

BWEnv/include/utils.h
BWEnv/src/controller.cc
BWEnv/src/utils.cc

reads and converts the string custom_launcher from the config file inside the conditional in controller.cc
but otherwise I do not think anything is diffferent from the other two methods of launching SC

derpy implementation of custom_launcher

---

BWEnv/fbs/messages.fbs
BWEnv/fbs/messages_generated.h
BWEnv/include/utils.h
BWEnv/src/controller.cc
BWEnv/src/utils.cc
client/state.cpp
include/frame.h
include/state.h
lua/state_lua.cpp
replayer/frame.cpp

This adds new information to the server-side handshake: a 2D array in build tile
resolution that indicates whether a building can be placed on a given tile.
Apart from that, the visibility information of units has been enhanced.
'visibile' has been changed to an integer that stores visibility bits for each
player in the game. The result of BWAPI's isDetected() function is stored in
'detected'.

Buildability data and enhanced unit visibility info

---

client/client.cpp
client/connection.cpp
client/connection.h
include/client.h

This is handy when locking access to torchcraft::State in client code, for
example, since Client::receive() will block until a reply from the server has
been received (or until a timeout occurs) before updating the game state.

Expose poll() in Client

---

include/constants.h

These are useful for map analysis purposes, e.g. via BWEM.

Add Special_Pit_Door and Special_Right_Pit_Door unit types

---

BWEnv/src/controller.cc
include/frame.h
lua/frame_lua.cpp
replayer/frame.cpp

There's a lot of unit status information accessible via BWAPI as booleans, and
so far we restricted the information in TorchCraft to idle, detected and
visible. However, flags like constructing can also be helpful in certain
situations such as tracking a worker's progress.
Hence, this includes a single 64-bit integer that stores various status bits.
Furthermore, the conditions for including a unit in the frame sent to the client
have been relaxed -- it's now upon the client to ignore units that are not of
interest.

Add status flags for units

---

BWEnv/include/controller.h
BWEnv/src/controller.cc
include/client.h
include/constants.h

This adds two new commands, DRAW_TEXT and DRAW_TEXT_SCREEN that make use of
BWAPI's text rendering functionality in pixel and screen coordinates,
respectively. This is useful for rendering debug information, for example.
The Client::Command constructors have been slightly refactored to enable
construction with a string argument alongside integer arguments.

Add basic text drawing commands

---

BWEnv/src/controller.cc
include/frame.h
lua/frame_lua.cpp

Unfortunately, this can't be deduced from existing flags.
'BeingConstructed' is set for buildings only and there is no 'BeingTrained' (there's
just 'Training', which applies to e.g. barracks training marine units).

Add 'Completed' to unit flags

---

examples/progressbar.lua
torchcraft-1.2-1.rockspec

cjson is not required any more, and we don't really need tds except for the
progress bar (where it just stores a single key).

Clean up dependencies in rockspec

---

CMakeLists.txt
include/replayer.h
lua/replayer_lua.cpp
replayer/replayer.cpp
replayer/zstdstream.h

This adds detection of zstd to the build system (reflected via the `WITH_ZSTD`
pre-processor symbol) and drop-in replacements for std::ifstream and
std::ofstream that read and write data using Zstd. zstd::ifstream will
automatically detected whether it is reading uncompressed data and will resort
to copy-through in this case.
Replayer is aware of Zstd support, which still has to be enabled explicitly by
the user at this point. In preliminary experiments, replay data could be
compressed by a huge factor, even when containing frame diffs. Please let
me know if you think it'll be a good idea to enable compression by default.
For testing, I used [this little script](https://gist.github.com/jgehring/b8625170bc00ed9bdc7813f3ccee3f9f) on a dump of the replay included in maps/
(bwrep_axkn5.rep). …

Zstd compression support for replays

---

BWEnv/fbs/messages.fbs
BWEnv/fbs/messages_generated.h
BWEnv/include/ZMQ_server.h
BWEnv/include/controller.h
BWEnv/src/controller.cc
BWEnv/src/zmq_server.cc
client/client.cpp
include/client.h

This adds a `commands_status` field to the server's Frame message. It contains a
return code for each command that the client issued in its previous message, in
the same order as the original commands. A return code of zero indicates
success, and any other value signals an error. This should be mainly useful for
debugging as it is tedious to constantly check the server's error log for failed
commands. Note that for every command issued via BWAPI, there is still a small
chance that it will fail even if its return code is zero.
The exact error codes are currently internal to the server code since I assumed
it would not be that useful to expose them on the client side. This can be
changed later, of course.

Add command status codes to server messages

---

BWEnv/src/controller.cc

Secondary orders will include the training of units, for example.
The primary order will be always included, even if it is nothing. This is because I don't
know the exact relationship between the order and `getTarget()/getTargetPosition()`:
I don't want to not exclude the current target just because the order happens to be nothing.

Include secondary orders in Unit::orders

---

py/pyreplayer.cpp

Pybind will take ownership of the returned Frame pointer, and tries to free it when it goes out of scope. Instead, Replayer should take onwership of this pointer and python should simply reference it. reference_internal keeps the parent Replayer alive as long as the Frame* is alive.

Fixing #122

---

BWEnv/include/utils.h
BWEnv/src/config_manager.cc
BWEnv/src/utils.cc

I originally implemented those functions with the same name as was
already used (windows api functions), but bwapi includes windows.h which
produces an error due to name collision.

Fix BWEnv compile on Windows :D

---

client/state.cpp
include/state.h
lua/state_lua.cpp
lua/state_lua.h

This moves the logic previously implemented as a side-effect of
pushUpdatesState() to a local helper function, updateUserValueAndPush().
Pre-defined user values are now computed whenever a uservalue entry is
requested. Caching is controlled by a new total update counter in State.

Update State uservalue on request

---

BWEnv/src/controller.cc

With a DLL, this happens because the module is reloaded, but with a client/openbw this seems to be necessary.

Reset battle_frame_count in MatchEnd, so it resets properly when doing a quit

---

examples/cpp/simple_dll.cpp
examples/simple_dll.lua

The unittype is always given as the last argument. This script currently works, but only because marines are unittype 0. It could be confusing to newcomers.

Fixing Train command in simple_dll

---

py/pyconstants.cpp
py/pyreplayer.cpp

- replayer.load can be multithreaded
- Removed compiler warning about types by an explicit type conversion
- Python constants now correctly have a ._dict that has an inverse mapping.

Python bugfixes / improvements

---

include/state.h
replayer/zstdstream.h

Also, zstd::dstream::defaultLevel was unused.

Added missing explicit constructors

---

py/pyclient.cpp

The client owns its state object, so the state's lifetime is tied to the
lifetime of the client. Return a reference via pybind to prevent potential
use-after-free issues if the Python state object outlives its client.

Python: Client.state() needs to return a reference

---

replayer/zstdstream.h

It's possible that the Zstd stream will not decompress any data but still asks
for more. I observed this in one instance in which Zstd would return '1' as a
hint for the size of the next chunk of input data, but when fed with a single
byte would not decompress anything. The previous implementation would ignore
this and pass the same pointer for all three arguments of setg(). This may cause
a segmentation fault or various other problems down the road (depending on
compiler and optimization level).

Fix possible decompression error in zstd::istreambuf

---

BWEnv/CMakeLists.txt
BWEnv/include/controller.h
BWEnv/include/zmq_server.h
BWEnv/src/controller.cc
client/client.cpp
docs/user/openbw.md
examples/py/create_kill.py
include/constants.h
lua/constants_lua.cpp
py/pyconstants.cpp

Untested, since `tsc-bw` is currently not compiling on clang. Waiting on @tscmoo to unbreak that before merging this into develop.
Also adds user commands to the python client.
Note: I don't want to add the rest of the new API to this PR, as they warrant more discussion.

Add OpenBW create / kill units interface

---

BWEnv/src/zmq_server.cc

This enables connections to BWEnv with both IPv4 and IPv6. If restricted to IPv4
only, there's an issue that appears on some non-Windows systems that prevents
establishing a connectiong with a TC client (which also supports both IPv4 and
IPv67).
I'll leave the Windows setup as is since it's functional it's a little bit of a
hassle for me to test IPv6 connectivity there.

BWEnv: support IPv6 on non-Windows systems

---

BWEnv/fbs/messages.fbs
BWEnv/fbs/messages_generated.h
BWEnv/include/controller.h
BWEnv/src/controller.cc
BWEnv/src/module.cc
client/state.cpp
include/frame.h
include/state.h
replayer/frame.cpp

Now the connection also uses frame diffs instead of the full frames.
I ran clang-format on every file this change touched, so a lot of this is automatic, sorry guys :( I'll split it into 2 commits next time. module.cc wasn't really changed much except for the destructor. 
In frame.h I removed all of the diff functions involving references, so we don't get an explosion of signatures that take either pointers or references,

Send frame diffs over instead of full frames

---

replayer/frame.cpp

Small bug in undiffing causes us to lose all unit attributes.

Fixing add when f and frame are the same

---

BWEnv/include/controller.h
BWEnv/src/controller.cc
examples/simple_dll.lua

Ran simple_dll for 270k frames, or a bit over 3 hours. #170

Remove two hours time limit on TC server

---

lua/init.lua

Units contain damage type information only. Fixes #177.

Return damage type instead of weapon type from get_weapon

---

BWEnv/src/controller.cc

buildTechUpgradeType returns BWAPI::UpgradeTypes::None.getID() instead of -1 when nothing matches.

Changes unit->buildTechUpgradeType to never return -1

---

examples/dump_replay.lua
include/frame.h
lua/frame_lua.cpp

Pass x and then y for the sake of consistency.

Change argument order for getCreepAt()

---

BWEnv/src/controller.cc

When in an UMS map and you cannot see your opponent's units, for some reason the Broodwar::getEnemy() is a nullptr sometimes.
This might just be in OpenBW @tscmoo

Fix pack units for UMS maps

---

BWEnv/include/controller.h
BWEnv/src/controller.cc
BWEnv/src/module.cc

Previously it would only be set in client mode, thus with module (dll/so) the game would always report as a loss.

Set is_winner correctly on game end when using a module.

---

BWEnv/VisualStudio/BWEnv.vcxproj
BWEnv/include/controller.h
BWEnv/include/module.h
BWEnv/include/zmq_server.h
BWEnv/src/controller.cc
BWEnv/src/dll.cc
BWEnv/src/main.cc
BWEnv/src/user_actions.cc
BWEnv/src/utils.cc
BWEnv/src/zmq_server.cc
docker/cuda/Dockerfile
docker/no-cuda/Dockerfile
docs/user/bwapi_on_linux.md

The only ugly hack here is the Winapi guards added before including `bwapi.h`, as VS2017 changes the way headers are imported, and as such it doesn't seem to be enough to define the variable in `Dll.cc` and `main.cc`.

Update TorchCraft to BWAPI 4.2.0 / VS2017

---

BWEnv/src/controller.cc

BWAPI won't provide HP of cloaked or burrowed units if we cannot detect them yet.

Disable HP check when packing units

---

BWEnv/src/controller.cc
client/state.cpp

Also, no need to use c_str() to get the player name from BWAPI.

Fix segfault on zero-length player names

---

BWEnv/include/controller.h
BWEnv/include/zmq_server.h
BWEnv/src/controller.cc
BWEnv/src/module.cc
BWEnv/src/zmq_server.cc
include/constants.h

In non-blocking mode, BWEnv will block the game for a specified maximum amount
of time only before continuing. This enables abiding time limits for a given
match-up without adding complicated timing logic to the TorchCraft client
program.
If the client does not send commands for the current frame back in time (e.g.
receive in BWEnv times out), the game continues and a new attempt to receive
them will take place in the very next frame and so on until we finally get a
reply. If BWEnv absolutely has to send the frame (e.g. the game or battle is
over), it will perform a blocking receive call before sending it to abide the
REQ/REP pattern.
Please note the interplay with the SET_COMBINE_FRAMES option: BWEnv can only
send frame data to the client after having a received a message with commands. …

Non-blocking mode for BWEnv

---

CMakeLists.txt
examples/py/dump_rep.py
include/replayer.h
lua/replayer_lua.cpp
py/pyreplayer.cpp
replayer/frame.cpp
replayer/replayer.cpp
setup.py

- No more torch7 dependencies on the C++ / Python side! Instead uses numpy arrays, and lua uses torch7 tensors. 
- Added a replay test for the python side
- Fixed a bug with dumping replays since.... 4 months ago? wtf?
Buildmap:
Walkmap:
Ground height map:
Creep maps (chronologically from frames 1, 1k, 2k, 3k, and 4k from the TL replay in the repo):
Lua also builds as expected.

No more TH dependency

---

replayer/frame.cpp

This reverts the changes to replayer/frame.cpp in commit
9a3f6772bbe7521a6fdab61d47c9915d0f861042.
I'm not sure regarding the root cause of @ebetica's recent change (see #221).

Fix frame diff application in State

---

lua/gamestore.h
lua/replayer_lua.cpp
lua/state_lua.cpp

https://github.com/TorchCraft/TorchCraft/issues/218
Compiling TorchCraft produced a bunch of warnings about signed/unsigned integer comparison. Now it doesn't.
@jgehring @ebetica @syhw

Fixed Lua wrapper warnings about signed/unsigned comparisons

---

BWEnv/fbs/messages.fbs
BWEnv/fbs/messages_generated.h
client/state.cpp
include/state.h
lua/state_lua.cpp
py/pystate.cpp

https://github.com/TorchCraft/TorchCraft/issues/213
I'll be issuing a series of pull requests which cover the full transition to binary serialization.
---
Adding the FlatBuffer types which will represent frame data.

(Binary Serialization Part 1) Updated TorchCraft IDL to include types for frame serialization

---

BWEnv/fbs/base.h
BWEnv/fbs/flatbuffers.h
BWEnv/fbs/gen.sh
BWEnv/fbs/messages.fbs
BWEnv/fbs/messages_generated.h
BWEnv/fbs/stl_emulation.h
client/state.cpp
include/state.h
lua/state_lua.cpp
py/pystate.cpp

https://github.com/TorchCraft/TorchCraft/issues/213
I'll be issuing a series of pull requests which cover the full transition to binary serialization.
---
Updating to FlatBuffers 1.7.1.
* Updated relevant FlatBuffers headers (it requires two more)
* Updated flatc invocation script to verify that we're using the correct version of FlatBuffers
@jgehring @ebetica @syhw

(Binary Serialization Part 0) Updated to latest version of FlatBuffers.

---

BWEnv/VisualStudio/BWEnv.sln
BWEnv/VisualStudio/BWEnv.vcxproj
BWEnv/src/controller.cc
include/flatbuffer_conversions.h

* Fixed MSVC error: Namespace-scope lambdas in header files need to be const or the linker suffers duplicate name confusion
* Fixed MSVC warning: unsigned integer comparison
* Set required Windows SDK version to be less specific
* Set default Visual Studio configuration to Release

MSVC error/warning fixes + better Visual Studio default settings

---

include/frame.h
replayer/frame.cpp

The existing assignment operator prohibits assignment from rvalues. Its implementation is a typical copy-and-swap operation, it is compatible with copy and move logic. So changing the unorthodox pass-by-reference (as compared to pass-by-const-reference) to pass-by-value.

Fix assignment operator for Frame

---

BWEnv/fbs/messages.fbs
BWEnv/fbs/messages_generated.h

Unit::visible contains visibility information for all players.

Fix type of visibility field in fbs definition

---

BWEnv/include/controller.h
BWEnv/src/controller.cc
examples/lua/dump_replay.lua
examples/py/dump_rep.py
include/constants.h

The `COMBINE_FRAMES` option takes either one or two arguments now. With two
argument, it allows setting a maximum number of combined frames. This is useful
in non-blocking mode, in which `COMBINE_FRAMES` previously acted as a *minimum*
number of combined frames. If a maximum is set, BWEnv will block and wait for a
client requests once the maximum number of combined frames has been reached.
The intended use-case is to speed up processing of replays. It's usually
desirable to have a constant number of combined frames per server reply (i.e.
setting `COMBINE_FRAMES` and enabling `BLOCKING`). However, waiting for a client
request does, in many cases, not make much sense because the client might not
issue any commands. With setting a minmum and maximum combination value  and
disabling …

Add ability to set maximum number of combined frames

---

py/pyclient.cpp

Check for empty command vectors before accessing their first element.
Fixes #247.

Fix segfault in Python client for empty command vectors.

---

BWEnv/VisualStudio/BWEnv.vcxproj

1. Due to the header files of torchcraft has been moved to include/torchcraft instead of include.
2. These changes are required so we can build BWEnv in Windows

fix torchcraft header path in BWEnv project file

---

client/state.cpp

The change is minimal, but it is quite significant.
Previously, only the controlled player would have their units filtered in `state.units`, while now the only units list that *won't* be filtered will be the neutral player's.
This allows us to maintain some consistency in the state, while also enabling us to consider some of the pro maps that use special neutral blocks to block paths without having to refer to `state.frame.units`.

Filter units for all controllable players

---

client/connection.cpp
client/connection.h

For training runs, we can easily have >80 active TorchCraft connections per
process (e.g. >40 self-play games running in parallel). Constantly constructing
and destructing a ZeroMQ context for each connection is both a waste of time and
resources, since each context will result in a dedicated I/O thread. This change
enables context sharing across across *active* connections -- once the last
connection is closed, the shared context is destroyed and re-created on the
next connection attempt.
I did some basic benchmarking, and for a relatively simple self-play game I saw
500 MBit going over the wire in total (send/receive for both players) within 30
seconds. Assuming twice the size for a more complex game, we'd hit 1 Gbps with
30 parallel games. The ZeroMQ FAQ …

Enable sharing of ZMQ context between active connections

---

README.md
docker/README.md
docker/openbw/Dockerfile

This PR adds a docker image that compiles OpenBW and BWEnv so that they are ready to use together. 
The build does not assume that the MPQs are available, and thus they need to be mounted at runtime. I've added instructions on how to do so in the README.

Add OpenBW docker image

---

client/client.cpp
client/state.cpp
include/torchcraft/state.h

`Client::receive()` will now return `false` upon error messages from the server.
`Client::error()` will contain the error message that was received.

Propagate server errors

---

BWEnv/include/zmq_server.h
BWEnv/src/controller.cc
BWEnv/src/zmq_server.cc

While it's possible to reconnect to a server and continue playing, controlling a
player with multiple clients at once is a strong indication that something is
wrong. It also results in clients receiving wrong (frame diff) data.
The ZMQ server will now keep track of the last client that performed a handshake
and will only accept commands from this client. Commands from any other client
will result in error messages being sent back. In blocking mode, the game will
not advance in this case; in non-blocking mode, the game will advance by one
frame but no commands will be executed.
With some refactoring, it would be possible to make this work correctly in
non-blocking mode as well. However, concurrent connections are considered an
error now (likely indicating another error in the client setup) …

Prevent concurrent connections from multiple clients

---

BWEnv/fbs/base.h
BWEnv/fbs/flatbuffers.h
BWEnv/fbs/gen.sh
BWEnv/fbs/messages.fbs
BWEnv/fbs/messages_generated.h
BWEnv/fbs/stl_emulation.h
BWEnv/include/zmq_server.h
BWEnv/src/controller.cc
client/client.cpp
client/state.cpp

This can be used for additional sanity checks in clients, e.g. when reconnecting
to a game that is already running.
I updated flatbuffers to 1.8.0, mostly because 1.7.1 can't be compiled from the
Github repo without additional effort (they did not add the correct version string
for the tag at https://github.com/google/flatbuffers/tree/v1.7.1).
EDIT: Naturally, this requires a bump for protocol version.

Add frame_from_bwapi to server handshake

---

BWEnv/CMakeLists.txt

This was required for compilation on macOS Mojave

Add missing include dir for BWEnv

---

BWEnv/fbs/messages.fbs
BWEnv/fbs/messages_generated.h
BWEnv/src/controller.cc
client/state.cpp
include/torchcraft/state.h
lua/init.lua
lua/state_lua.cpp
py/pystate.cpp

Adds map names to TC state info. We already had map file names (eg. BWAPI::Game::mapFileName()) but those aren't very useful for replays, as the file name is the replay name (ie. you can't tell what the original map was).
This adds the actual map name (BWAPI::Game::mapName()). Unfortunately, with `map_name` already being taken, this calls it `map_title` (per @tscmoo 's suggestion)

Real map names
