TorchCraft/TorchCraft

docs/user/installation.md

See https://github.com/TorchCraft/TorchCraft/issues/5

Fix link to BWEnv.dll and exe

---

docs/user/bwapi_on_linux.md
quick_setup.sh

I fixed the install script and doc for Mac users.

Install script and doc patch for Mac

---

CMakeLists.txt
client/client.cpp
client/client.h
client/client_lua.cpp
client/client_lua.h
client/connection.cpp
client/connection.h
client/lua.cpp
client/zmq.hpp
init.lua

This is a first simple version of a C++ client. Right now, it handles network
connection, initial handshake and game state.  init.lua has been changed to use
the new client object for these functions. The Lua interface of the Torch
library itself has not been changed.
For now, the pure C++ layer is very thin and most of the functionality is
provided by the Lua wrapper, mostly because data from the server is sent as Lua
code.

Simple C++ client

---

examples/tensor_example.lua
examples/visual_example.lua

The local flag is `micro_game`, not `microgame`.

Fixed micro battle typos in examples

---

client/client.cpp
client/client.h
client/client_lua.cpp
client/connection.cpp
client/connection.h
client/state.cpp
client/state.h
client/state_lua.cpp
client/state_lua.h
init.lua

These are the client-side changes necessary to update the wire protocol to use
flatbuffers. The code responsible for applying state updates from Lua code has
been removed.

Use flatbuffers for wire protocol (client-side changes)

---

include/client.h

This makes it more convenient to construct commands in C++ code.

Add constructors for Client::Command

---

include/replayer.h
replayer/replayer.cpp

size_t can't be smaller than 0

Remove tautological comparisons in replayer.{h,cpp}

---

docs/user/installation.md

Fixes https://github.com/TorchCraft/TorchCraft/issues/69

Adding documentation about BWAPI_DIR

---

replayer/frame.cpp

L350 and L276 are the real changes, all the others are just clang-formats

Fix frame diff bug where it crashes when all neutrals die

---

BWEnv/src/controller.cc
BWEnv/src/utils.cc
lua/state_lua.cpp

@edran, I assume this will affect the drawing commands in init.lua?

Don't transpose map data, fix tensor representation

---

client/state.cpp
include/state.h
lua/state_lua.cpp

This makes working with frame data in C++ more convenient.

TC namespace aliases for basic replayer types

---

lua/replayer_lua.cpp
lua/replayer_lua.h

So we can save replays with a different keyframe straight from lua :)

Added keyframes to lua

---

BWEnv/src/controller.cc
include/frame.h
lua/frame_lua.cpp
replayer/frame.cpp

Also, the Lua wrapper for Frame missed recent attributes and still returned a
boolean for visible.

Add lifted attribute to Unit

---

CMakeLists.txt
quick_setup.sh
torchcraft-1.2-1.rockspec

- #82 Don't transpose map data, fix tensor representation
- #84 TC namespace aliases for basic replayer types
- #85 Added keyframes to lua
- #86 Buildability data and enhanced unit visibility info
- #87 Order static data by unit type value
- #88 Add lifted attribute to Unit
- #89 Expose poll() in Client

Bump minor version (v1.2-1)

---

BWEnv/fbs/messages.fbs
BWEnv/include/ZMQ_server.h
client/client.cpp

This was long overdue as we changed the frame data multiple times already.

Bump protocol version for binary formats

---

BWEnv/src/controller.cc
include/frame.h
lua/frame_lua.cpp
replayer/frame.cpp

The is the command return by BWAPI's getLastCommand(), along with the frame
information from getLastCommandFrame().

Add last command to unit

---

.clang-format
examples/dump_replay.lua
include/frame.h
include/replayer.h
lua/frame_lua.cpp
replayer/frame.cpp

This way, when we push frames and never make a new pointer, it won't bug out.
I also did a clang-format on `include/frame.h`, although I think it looked better before the clang format...

pushFrame now does a copy

---

examples/dump_replay.lua
include/replayer.h
lua/replayer_lua.cpp
replayer/replayer.cpp

Fixes https://github.com/TorchCraft/TorchCraft/issues/107.

Adding the ability to pass a torchcraft state to setMap

---

BWEnv/include/config_manager.h
BWEnv/include/recorder.h
BWEnv/include/utils.h
BWEnv/src/config_manager.cc
BWEnv/src/controller.cc
BWEnv/src/main.cc
BWEnv/src/user_actions.cc
BWEnv/src/utils.cc
BWEnv/src/zmq_server.cc

This only fixes compilation and running issues on Linux/non-windows, it does not include any openbw code.

Fix BWEnv compile on linux

---

py/pyconstants.cpp
py/pyreplayer.cpp

Implements #117. 
Also fixed segfault that would sometimes happen, since Enum::MAX would sometimes be out of range of the respective arrays.

Added getMap to python client.

---

replayer/zstdstream.h

Fix return value of zstd::istreambuf::underflow

---

py/pyreplayer.cpp
replayer/replayer.cpp

- fixes https://github.com/TorchCraft/TorchCraft/issues/134
- adds a setMap, so we can change and save replays more easily on python.

Adding setMap and throwing nicer error on bad ifstream

---

py/pyclient.cpp

Python: fix return value policy for Client.state()

---

lua/lua_utils.cpp
lua/lua_utils.h
lua/state_lua.cpp
lua/state_lua.h

This will also clone (i.e. deep-copy) the uservalues associated with this state.

Lua: add State:clone()

---

client/state.cpp
include/frame.h
include/state.h
lua/lua_utils.cpp
lua/lua_utils.h
lua/state_lua.cpp
lua/state_lua.h
py/pystate.cpp

This adds proper copy and move support for Frame and State, i.e. constructors
and operators.

Copy and move support for Frame and State

---

BWEnv/src/zmq_server.cc

by correctly sending the handshake on reconnect if we are in a game

Fix reconnecting with client/openbw

---

replayer/frame.cpp
replayer/replayer.cpp

@tscmoo are there tighter bounds I can use?

Adding more checks during replay reading

---

BWEnv/src/zmq_server.cc

It fails to compile without this >.<

Include BWAPI/Client.h in zmq_server.cc.

---

CMakeLists.txt
py/setup.py
quick_setup.sh
torchcraft-1.3-0.rockspec

Auto: Update version files to v1.3-0

---

py/setup.py
setup.py

Also looks in the pytorch directory and uses `which th` to find the includes

More robust python setup

---

setup.py
torchcraft-1.3-1.rockspec

Before:
pip3 install .  43.18s user 2.96s system 99% cpu 46.516 total
After:
pip3 install .  62.00s user 3.36s system 358% cpu 18.257 total
Similar speedups for luarocks.

Parallel builds for lua and python

---

client/state.cpp
examples/py/example.py
examples/simple_dll.lua
include/state.h

Recent update to sending diffs introduced this bug. I'm also changing the restarts to quit, since restart isn't implemented in openbwapi.

Fixing bug where end game would crash

---

BWEnv/src/zmq_server.cc

Also, print the selected port to stdout for debugging purposes and interop when
launching the module from scripts.

Use IPv6 with automatic port selection in BWEnv

---

BWEnv/src/controller.cc

Fix buildTechUpgradeType

---

BWEnv/fbs/messages.fbs
BWEnv/fbs/messages_generated.h
BWEnv/include/controller.h
BWEnv/include/zmq_server.h
BWEnv/src/controller.cc
BWEnv/src/zmq_server.cc
CMakeLists.txt
client/client.cpp
client/state.cpp
examples/cpp/simple_dll.cpp
examples/py/example.py
examples/simple_dll.lua
include/constants.h
include/replayer.h
include/state.h
lua/constants_lua.cpp
lua/state_lua.cpp
py/pyconstants.cpp
py/pystate.cpp
replayer/frame.cpp
replayer/replayer.cpp
setup.py
torchcraft-1.3-2.rockspec

adding races to state via handshake

Add races to tc.state

---

BWEnv/fbs/messages.fbs
BWEnv/fbs/messages_generated.h
BWEnv/include/zmq_server.h
BWEnv/src/controller.cc
CMakeLists.txt
client/client.cpp
client/state.cpp
examples/cpp/simple_dll.cpp
examples/py/example.py
examples/simple_dll.lua
include/state.h
lua/state_lua.cpp
py/pystate.cpp
setup.py
torchcraft-1.3-3.rockspec

trying to find a way for flatbuffer to generate me a `[string] -> vector<string>`

Add player names

---

client/client.cpp
client/state.cpp
include/client.h
include/state.h

Client apps might not want to account for deaths twice.

Always clear State::deaths on server updates

---

BWEnv/fbs/messages.fbs
BWEnv/fbs/messages_generated.h
BWEnv/src/controller.cc
client/state.cpp
examples/cpp/simple_dll.cpp
examples/py/example.py
examples/simple_dll.lua
include/state.h
lua/state_lua.cpp
py/pystate.cpp

On the wire, this is an array of PlayerInfo structs that each contain the ID,
race and name of every player and a boolean that indicates whether the player is
an enemy or not.
For the client, the information is exposed as a map from player IDs to
aforementioned PlayerInfo structures for easy access by player ID.

Replace player_races and player_names with "players"

---

client/state.cpp
include/state.h
lua/state_lua.cpp
py/pystate.cpp

#213
I'll be issuing a series of pull requests which cover the full transition to binary serialization. 
---
Removing references to the obsolete frame_string.

(Binary Serialization Part 2) Removing frame_string

---

include/streaming_flatbuffers.h
replayer/frame_diff.cpp
replayer/frame_diff_serialization.cpp
replayer/frame_serialization.cpp

`python examples/py/dump_rep.py` seems to work again.

Fixing replay saving

---

include/streaming_flatbuffers.h
py/pyreplayer.cpp
replayer/frame_diff.cpp
replayer/frame_diff_serialization.cpp
replayer/frame_serialization.cpp
setup.py

Python client was no longer working for me without these fixes...

Remove torch from python, fix some compile errors

---

py/pyclient.cpp
setup.py

Whomp, also adds the option to use a file socket to the python client.
#269

Fix python setup.py after zmq file_socket change

---

BWEnv/include/controller.h
BWEnv/src/controller.cc
include/torchcraft/constants.h

SET_PLAYER_UPGRADE_LEVEL, SET_PLAYER_RESEARCHED, SET_PLAYER_MINERALS,  SET_PLAYER_GAS, SET_UNIT_HEALTH, SET_UNIT_SHIELD, SET_UNIT_ENERGY
Someone test for me if this actually works . @ebetica? 😅

Added some openbw commands for cheats
